version: "3.1"
services: 
  db:
    image: postgres
    restart: always
    ports:
      - "6661:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shopinglist
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - "8020:8080"
